### ISSUE TITLE
CUDA Version: Not available when trying to install SageAttention

### ISSUE THREAD

**Issue by samgermain** [Tavris1/ComfyUI-Easy-Install#89]
When I run the SageAttention install script, it's telling me the CUDA version is unavailable

```
$ ./Add-Ons/SageAttention-NEXT.sh 

::::::::::::::: Clearing Pip Cache Done

::::::::::::::: Checking Python, Torch, CUDA versions

::::::::::::::: Python Version: 3.12
::::::::::::::: Torch Version: 2.9
::::::::::::::: CUDA Version: Not available

WARNING: CUDA Not available is not supported. Supported version: 12.8

::::::::::::::: Press any key to exit
```

But I do have a CUDA

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:18:24_PDT_2024
Cuda compilation tools, release 12.4, V12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0
```

This is my OS

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by VenimK** [comment]
Morning.

`$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:18:24_PDT_2024
Cuda compilation tools, release 12.4, V12.4.131
Build `cuda_12.4.r12.4/compiler.34097967_0``


Cuda 12.4 that looks like it
Whats ya vidcard
What your latest driver..
I'l get back to ya asap [working]
If ya can provide more info on that i can take a closer look

Thx 4 the feedback

**Comment by altoiddealer** [comment]
I had the same issue when installing this on a second machine.

I think the issue has to do with outdated (possibly faulty?) drivers, as the comment from @VenimK prompted me to update my Nvidia drivers, then the problem went away.

So, it might be a good idea to include some kind of log warning when No Cuda is found after install?  Something like: try updating your graphics drivers and restart the installation

**Comment by samgermain** [comment]
> Morning.
> 
> `$ nvcc --version nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2024 NVIDIA Corporation Built on Thu_Mar_28_02:18:24_PDT_2024 Cuda compilation tools, release 12.4, V12.4.131 Build `cuda_12.4.r12.4/compiler.34097967_0``
> 
> Cuda 12.4 that looks like it Whats ya vidcard What your latest driver.. I'l get back to ya asap [working] If ya can provide more info on that i can take a closer look
> 
> Thx 4 the feedback

is this all the information you need?

```
$ nvidia-smi
Mon Jan  5 06:25:57 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P0             26W /   70W |     155MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A   1099628      C   python                                        152MiB |
+-----------------------------------------------------------------------------------------+
```

I'm using a gcloud VM with OS

```
Deep Learning on Linux
Deep Learning VM with CUDA 12.4 M129
Debian 11, Python 3.10. With CUDA 12.4 preinstalled.
```

and a Nvidia T4

**Comment by VenimK** [comment]
[SageAttention-NEXT.sh](https://github.com/user-attachments/files/24428188/SageAttention-NEXT.sh)

Try to run this one ....


EDITED this in file ....
`if` [[ "$CUDA_VERSION" != "12.4" && "$CUDA_VERSION" != "12.8" ]]; then
    echo -e "${warning}WARNING: ${red}CUDA $CUDA_VERSION is not supported. ${green}Supported versions: 12.4, 12.8${reset}"
    WARNINGS=1
`fi`

**Comment by samgermain** [comment]
> [SageAttention-NEXT.sh](https://github.com/user-attachments/files/24428188/SageAttention-NEXT.sh)
> 
> Try to run this one ....
> 
> EDITED this in file .... `if` [[ "$CUDA_VERSION" != "12.4" && "$CUDA_VERSION" != "12.8" ]]; then echo -e "${warning}WARNING: ${red}CUDA C U D A V E R S I O N i s n o t s u p p o r t e d . {green}Supported versions: 12.4, 12.8${reset}" WARNINGS=1 `fi`

No that didn't work, 

After i upgraded cuda to 12.8, what worked for me was

```
if command -v nvcc &>/dev/null; then
    CUDA_VERSION=$(nvcc --version | grep -oP "V\K[0-9]+\.[0-9]+")
elif "$PYTHON_PATH"; then
   CUDA_VERSION=$("$PYTHON_PATH" -c "import torch; print(torch.version.cuda if torch.cuda.is_available() else 'Not available')" 2>/dev/null | cut -d'.' -f1,2)
fi
```
around line 51

I also needed to update triton to 3.5.1 on line 133

but I am still getting

```
Collecting git+https://github.com/thu-ml/SageAttention
  Cloning https://github.com/thu-ml/SageAttention to /var/tmp/pip-req-build-7ywwc7bh
  Running command git clone --filter=blob:none --quiet https://github.com/thu-ml/SageAttention /var/tmp/pip-req-build-7ywwc7bh
  Resolved https://github.com/thu-ml/SageAttention to commit 5a6f53c77975abc039bf3ec5cb4c789b44f90771
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      ~/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/lib/python3.12/site-packages/torch/cuda/__init__.py:182: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 12040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:119.)
        return torch._C._cuda_getDeviceCount() > 0
      W0105 07:49:12.260000 1154338 torch/utils/cpp_extension.py:117] No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
      Traceback (most recent call last):
        File "~/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "~/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "~/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "~/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/lib/python3.12/site-packages/setuptools/build_meta.py", line 374, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "~/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/lib/python3.12/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
        File "<string>", line 124, in <module>
      RuntimeError: No target compute capabilities. Set TORCH_CUDA_ARCH_LIST or build on a machine with GPUs.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

when i run this script

**Comment by samgermain** [comment]
it's turn out my nvidia driver didn't actually update to 12.8

**Comment by VenimK** [comment]
> it's turn out my nvidia driver didn't actually update to 12.8

All good then 4 now ....

**Comment by samgermain** [comment]
> > it's turn out my nvidia driver didn't actually update to 12.8
> 
> All good then 4 now ....

no, the problems i described above are still happening, i was able to update my nvidia driver though

**Comment by samgermain** [comment]
> > it's turn out my nvidia driver didn't actually update to 12.8
> 
> All good then 4 now ....

If you want to test out the environment im using, you can set up a google cloud VM, you need to create a paid account, but the free tier should cover your usage for this. I'm creating instructions here. You'll need to run `install-driver.sh` to get the driver for cuda 12.8, and then you can look at install-comfyui.sh to see what else I'm using. There's no instructions for ComfyUI-Easy-Install because I haven't gotten it working yet

https://github.com/samgermain/comfyui-google-cloud-setup

**Comment by VenimK** [comment]
> > > it's turn out my nvidia driver didn't actually update to 12.8
> > 
> > 
> > All good then 4 now ....
> 
> If you want to test out the environment im using, you can set up a google cloud VM, you need to create a paid account, but the free tier should cover your usage for this. I'm creating instructions here. You'll need to run `install-driver.sh` to get the driver for cuda 12.8, and then you can look at install-comfyui.sh to see what else I'm using. There's no instructions for ComfyUI-Easy-Install because I haven't gotten it working yet
> 
> https://github.com/samgermain/comfyui-google-cloud-setup

I,l test it 2night
Thx

**Comment by VenimK** [comment]
> > > it's turn out my nvidia driver didn't actually update to 12.8
> > 
> > 
> > All good then 4 now ....
> 
> If you want to test out the environment im using, you can set up a google cloud VM, you need to create a paid account, but the free tier should cover your usage for this. I'm creating instructions here. You'll need to run `install-driver.sh` to get the driver for cuda 12.8, and then you can look at install-comfyui.sh to see what else I'm using. There's no instructions for ComfyUI-Easy-Install because I haven't gotten it working yet
> 
> https://github.com/samgermain/comfyui-google-cloud-setup

This takes 4ever to load the instance ????
I could see, you can load a machine with Cuda 12.8
Ya might choose that as well

**Comment by samgermain** [comment]
> > > > it's turn out my nvidia driver didn't actually update to 12.8
> > > 
> > > 
> > > All good then 4 now ....
> > 
> > 
> > If you want to test out the environment im using, you can set up a google cloud VM, you need to create a paid account, but the free tier should cover your usage for this. I'm creating instructions here. You'll need to run `install-driver.sh` to get the driver for cuda 12.8, and then you can look at install-comfyui.sh to see what else I'm using. There's no instructions for ComfyUI-Easy-Install because I haven't gotten it working yet
> > https://github.com/samgermain/comfyui-google-cloud-setup
> 
> This takes 4ever to load the instance ???? I could see, you can load a machine with Cuda 12.8 Ya might choose that as well

What do you mean by takes forever to load the instance? Also, I could only see up to cuda 12.4 for machines

**Comment by samgermain** [comment]
It works now, I need to run the torch installation script for 2.8 (it looks like the 2.9 script is specific to cuda 13

```
$ ./Add-Ons/Torch2.8.0+cu128.sh
```

but then I get

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.8.0+cu128 requires triton==3.4.0; platform_system == "Linux" and platform_machine == "x86_64", but you have triton 3.5.0 which is incompatible.
Successfully installed triton-3.5.0
```

I don't know if this will cause problems

**Comment by VenimK** [comment]
> > > > > it's turn out my nvidia driver didn't actually update to 12.8
> > > > 
> > > > 
> > > > All good then 4 now ....
> > > 
> > > 
> > > If you want to test out the environment im using, you can set up a google cloud VM, you need to create a paid account, but the free tier should cover your usage for this. I'm creating instructions here. You'll need to run `install-driver.sh` to get the driver for cuda 12.8, and then you can look at install-comfyui.sh to see what else I'm using. There's no instructions for ComfyUI-Easy-Install because I haven't gotten it working yet
> > > https://github.com/samgermain/comfyui-google-cloud-setup
> > 
> > 
> > This takes 4ever to load the instance ???? I could see, you can load a machine with Cuda 12.8 Ya might choose that as well
> 
> What do you mean by takes forever to load the instance? Also, I could only see up to cuda 12.4 for machines

<img width="1996" height="781" alt="Image" src="https://github.com/user-attachments/assets/46f197ac-f351-4510-9ca1-245c5d380751" />



and , why don 't ya start with this installer
might be easier to pin point errors and so

https://github.com/Tavris1/ComfyUI-Easy-Install/tree/MAC-Linux

**Comment by samgermain** [comment]
> 
> and , why don 't ya start with this installer might be easier to pin point errors and so
> 
> https://github.com/Tavris1/ComfyUI-Easy-Install/tree/MAC-Linux

I can't believe i missed that.

I've already tried using that installer, i was running into issues with nunchaku 1.1.0, i tried setting nunchaku to 1.0.2 but something was using 1.1.0 anyway. I've installed Cuda 13 now and am using  nunchaku 1.1.0 now, so I don't think I'm going to use ComfyUI-Easy-Install because with SageAttention it can use Cuda > 12.8, but nunchaku 1.1.0 requires cuda 13.0

I'm still running into this issue though

```
# ComfyUI Error Report
## Error Details
- **Node ID:** 3
- **Node Type:** KSampler
- **Exception Type:** AttributeError
- **Exception Message:** 'list' object has no attribute 'dtype'

## Stack Trace
  File "~/ComfyUI/execution.py", line 518, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/execution.py", line 329, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/execution.py", line 303, in _async_map_node_over_list
    await process_inputs(input_dict, i)

  File "~/ComfyUI/execution.py", line 291, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^

  File "~/ComfyUI/nodes.py", line 1538, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/nodes.py", line 1505, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/sample.py", line 60, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion/utils.py", line 51, in KSampler_sample
    return orig_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 1178, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 1068, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 1050, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, latent_shapes=latent_shapes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 994, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, latent_shapes=latent_shapes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 980, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion/utils.py", line 34, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 752, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/k_diffusion/sampling.py", line 202, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 401, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 953, in __call__
    return self.outer_predict_noise(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 960, in outer_predict_noise
    ).execute(x, timestep, model_options, seed)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 963, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 381, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 206, in calc_cond_batch
    return _calc_cond_batch_outer(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 214, in _calc_cond_batch_outer
    return executor.execute(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/samplers.py", line 326, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/model_base.py", line 162, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/model_base.py", line 204, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/ldm/qwen_image/model.py", line 411, in forward
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/custom_nodes/ComfyUI-nunchaku/models/qwenimage.py", line 726, in _forward
    else self.time_text_embed(timestep, guidance, hidden_states)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/ComfyUI/comfy/ldm/qwen_image/model.py", line 81, in forward
    timesteps_emb = self.timestep_embedder(timesteps_proj.to(dtype=hidden_states.dtype))
                                                                   ^^^^^^^^^^^^^^^^^^^

## System Information
- **ComfyUI Version:** 0.7.0
- **Arguments:** ~/ComfyUI/main.py --listen 0.0.0.0 --port 8188
- **OS:** linux
- **Python Version:** 3.12.1 (main, Jan  3 2026, 06:53:37) [GCC 10.2.1 20210110]
- **Embedded Python:** false
- **PyTorch Version:** 2.9.1+cu130
## Devices

- **Name:** cuda:0 Tesla T4 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 15637086208
  - **VRAM Free:** 15506145280
  - **Torch VRAM Total:** 33554432
  - **Torch VRAM Free:** 33554432

## Logs
```

**Comment by VenimK** [comment]
Does it work with the default installer then.

Kinda don 't understand, why you are trying to install things, that are not needed by default.
Make it work from default, Then go with eventual Add-Ons.....

Can I have access to on your VM instance.
to check what's really going on

**Comment by samgermain** [comment]
> Does it work with the default installer then.
> 
> Kinda don 't understand, why you are trying to install things, that are not needed by default. Make it work from default, Then go with eventual Add-Ons.....
> 
> Can I have access to on your VM instance. to check what's really going on

whats your discord? mine is samweow, I'll send you the information on there

**Comment by samgermain** [comment]
I created a new glcoud VM with 

- Deep Learning VM with CUDA + Pytorch M131
- T4 GPU
- 30 GB ram, 8 vCPU

After setting up the firewall rule, ssh rules and allowing http traffic (instructions here: https://github.com/samgermain/comfyui-google-cloud-setup), I ran this to install ComfyUI, get the models ...

```sh
git clone --single-branch --branch MAC-Linux https://github.com/Tavris1/ComfyUI-Easy-Install.git
cd ComfyUI-Easy-Install/
chmod +x ComfyUI-Easy-Install.sh
./ComfyUI-Easy-Install.sh
cd ComfyUI-Easy-Install/
./Add-Ons/Torch2.7.1+cu128.sh 
./Add-Ons/Nunchaku-NEXT.sh 
./Add-Ons/SageAttention-NEXT.sh 
rm -rf ~/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/user/default/workflows
git clone https://github.com/samgermain/comfyui-workflows ~/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/user/default/workflows
wget --header="Authorization: Bearer ${HF_TOKEN}" https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/vae/qwen_image_vae.safetensors -P ~/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/models/vae
wget --header="Authorization: Bearer ${HF_TOKEN}" https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/text_encoders/qwen_2.5_vl_7b_fp8_scaled.safetensors -P ~/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/models/clip
wget --header="Authorization: Bearer ${HF_TOKEN}" https://huggingface.co/nunchaku-tech/nunchaku-qwen-image-edit-2509/resolve/main/svdq-int4_r128-qwen-image-edit-2509-lightningv2.0-4steps.safetensors -P ~/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/models/diffusion_models
~/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/bin/python ~/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/main.py --listen 0.0.0.0 --port 8188
```

The KSampler on Nunchaku is not working though, I'm getting this error

## Error Details
- **Node ID:** 3
- **Node Type:** KSampler
- **Exception Type:** AttributeError
- **Exception Message:** 'list' object has no attribute 'dtype'

## Stack Trace
```
  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/execution.py", line 518, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/execution.py", line 329, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/execution.py", line 303, in _async_map_node_over_list
    await process_inputs(input_dict, i)

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/execution.py", line 291, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/nodes.py", line 1542, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/nodes.py", line 1509, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/sample.py", line 60, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion/utils.py", line 51, in KSampler_sample
    return orig_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/samplers.py", line 1178, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/samplers.py", line 1068, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/samplers.py", line 1050, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, latent_shapes=latent_shapes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/samplers.py", line 994, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, latent_shapes=latent_shapes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/samplers.py", line 980, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion/utils.py", line 34, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/samplers.py", line 752, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/k_diffusion/sampling.py", line 202, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/samplers.py", line 401, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/samplers.py", line 953, in __call__
    return self.outer_predict_noise(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/samplers.py", line 960, in outer_predict_noise
    ).execute(x, timestep, model_options, seed)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/samplers.py", line 963, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/samplers.py", line 381, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/samplers.py", line 206, in calc_cond_batch
    return _calc_cond_batch_outer(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/samplers.py", line 214, in _calc_cond_batch_outer
    return executor.execute(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/samplers.py", line 326, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/model_base.py", line 163, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/model_base.py", line 205, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/ldm/qwen_image/model.py", line 411, in forward
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/patcher_extension.py", line 112, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/custom_nodes/ComfyUI-nunchaku/models/qwenimage.py", line 726, in _forward
    else self.time_text_embed(timestep, guidance, hidden_states)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/comfy/ldm/qwen_image/model.py", line 81, in forward
    timesteps_emb = self.timestep_embedder(timesteps_proj.to(dtype=hidden_states.dtype))
                                                                   ^^^^^^^^^^^^^^^^^^^

## System Information
- **ComfyUI Version:** 0.7.0
- **Arguments:** /home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/ComfyUI/main.py --listen 0.0.0.0 --port 8188
- **OS:** linux
- **Python Version:** 3.12.3 (main, Nov  6 2025, 13:44:16) [GCC 13.3.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.9.1+cu128
## Devices

- **Name:** cuda:0 Tesla T4 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 15638134784
  - **VRAM Free:** 15530262528
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0
```


I'm also having trouble installing SageAttention

```
./Add-Ons/SageAttention-NEXT.sh 

::::::::::::::: Clearing Pip Cache Done

::::::::::::::: Checking Python, Torch, CUDA versions

::::::::::::::: Python Version: 3.12
::::::::::::::: Torch Version: 2.9
::::::::::::::: CUDA Version: 12.8

::::::::::::::: All versions are supported! 

::::::::::::::: Checking Python development headers

::::::::::::::: Python development headers found!

::::::::::::::: Installing build dependencies

Collecting wheel
  Downloading wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: setuptools in /home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/lib/python3.12/site-packages (80.9.0)
Downloading wheel-0.45.1-py3-none-any.whl (72 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 3.4 MB/s eta 0:00:00
Installing collected packages: wheel
Successfully installed wheel-0.45.1

::::::::::::::: Installing Triton

Collecting triton==3.5.0
  Downloading triton-3.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Downloading triton-3.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (170.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.5/170.5 MB 310.0 MB/s eta 0:00:00
Installing collected packages: triton
  Attempting uninstall: triton
    Found existing installation: triton 3.5.1
    Uninstalling triton-3.5.1:
      Successfully uninstalled triton-3.5.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.9.1 requires triton==3.5.1; platform_system == "Linux" and platform_machine == "x86_64", but you have triton 3.5.0 which is incompatible.
Successfully installed triton-3.5.0

::::::::::::::: Checking CUDA toolkit (CUDA_HOME)

::::::::::::::: CUDA_HOME: /usr/local/cuda

::::::::::::::: Installing SageAttention

Collecting git+https://github.com/thu-ml/SageAttention
  Cloning https://github.com/thu-ml/SageAttention to /tmp/pip-req-build-318u4ih9
  Running command git clone --filter=blob:none --quiet https://github.com/thu-ml/SageAttention /tmp/pip-req-build-318u4ih9
  Resolved https://github.com/thu-ml/SageAttention to commit 5a6f53c77975abc039bf3ec5cb4c789b44f90771
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      <string>:117: UserWarning: skipping GPU 0 with compute capability 7.5
      Traceback (most recent call last):
        File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/lib/python3.12/site-packages/setuptools/build_meta.py", line 374, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/home/carmelizedsam/ComfyUI-Easy-Install/ComfyUI-Easy-Install/python_embeded/lib/python3.12/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
        File "<string>", line 124, in <module>
      RuntimeError: No target compute capabilities. Set TORCH_CUDA_ARCH_LIST or build on a machine with GPUs.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

::::::::::::::: Creating run_nvidia_gpu_SageAttention.sh

chmod: unrecognized option '--disable-pinned-memory'
Try 'chmod --help' for more information.

:::::::::::::::  Installation Complete

::::::::::::::: Press any key to exit
```
